### ISSUE TITLE
'HSUSBD_T' does not name a type

### ISSUE THREAD

**Issue by tm-sanjay** [OpenNuvoton/NuEdu-UNO#17]
```
from C:\Users\S\AppData\Local\Temp\arduino_build_281475\sketch\Blink.ino.cpp:1:
C:\Users\Sanjay\AppData\Local\Arduino15\packages\nuvoton\hardware\nuvoton\2.5.0\cores\nuvoton/HardwareSerial.h:86:27: error: expected ')' before '*' token
     HardwareSerial(VCOM_T *vcom_device, ring_buffer *rx_buffer);
                           ^
C:\Users\S\AppData\Local\Arduino15\packages\nuvoton\hardware\nuvoton\2.5.0\cores\nuvoton/HardwareSerial.h:47:23: error: 'HSUSBD_T' does not name a type
 #define VCOM_T        HSUSBD_T
                       ^
C:\Users\S\AppData\Local\Arduino15\packages\nuvoton\hardware\nuvoton\2.5.0\cores\nuvoton/HardwareSerial.h:109:5: note: in expansion of macro 'VCOM_T'
     VCOM_T *vcom_device;
     ^~~~~~
exit status 1
Error compiling for board NuMaker-NUC131U.
```
Getting this error after updating to v2.5

**Comment by stanlytw** [comment]
Hi, we have updated version to solve this issue. Please update v2.5.1. Thanks!

**Comment by tm-sanjay** [comment]
Thank you for the update it's working now
